title: Adi Gunawan  # Add a space after the period

logo: profile.png # Use a relative path to logo image 

description: ATM Development Engineer # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: Inbox.adigunawan@gmail.com # Allow visitors to contact you
